### ISSUE TITLE
Git time injection formatting

### ISSUE THREAD

**Issue by briggleman** [Darkyenus/DarkyenusTimeTracker#17]
Time tracking software like Jira requires specific formatting.  Would it be possible to add an enhancement to specify the format as well as the MBU (minimum billable unit, e.g. 1 minute, ect).

**Comment by Darkyenus** [comment]
Can you please provide examples/documentation to define the scope for this feature? That is, what should be the elements of the duration format and how should MBU feature work?

**Comment by briggleman** [comment]
### Formatting for Time Tracking
I think this would be best implemented as some sort of template structure.

For example, include a text box that allows the user to enter the commit message that should be appended to the commit along the format of the time.

```
commit message: #time {{ weeks }}w {{ days }}d {{ hours }}h {{ minutes }}
```
Would result in the following time comment being appended to the commit for a 1 day 2 hour project.

```
my commit.  #time 0w 1d 2h 0m
```

This would allow the greatest flexibility between the different time tracking software.

Optionally, using the templating method it would be nice to specify `int` or `float` for the different numbers since some time tracking software supports it, e.g. `#time `1.2w`

Documentation: [Jira Smart Commits](https://confluence.atlassian.com/fisheye/using-smart-commits-298976812.html#id-_smart_commits_commands-time)

Similar functionality: [Timeglass](https://github.com/timeglass/glass/blob/master/docs/config.md)

### Minimum Billable Unit (MBU)
MBU is simply a roll-up of the time logged to the nearest MBU. 

Example:

If MBU is 15 minutes and 14 minutes has been logged 15 minutes will be added to the commit since the MBU is 15 minutes.  Likewise, if time logged was 1 hour 10 minutes.

MBU should ideally be split from this request since both can be worked in tandem.

**Comment by Darkyenus** [comment]
Ok, so how about this:

### Formatting
Time will be always appended as the last line of the commit message (as it is now). What is printed can be specified by the format string, which can be arbitrary text that includes format patterns. Format pattern is enclosed in `{{` and `}}` (it is not possible to have `{{` and `}}` appear verbatim in the result, some sort of escaping could mitigate this, but that can be added later if needed). Format pattern uses units, specified by following:
```
<u> = unit placeholder, one of:
s - second
m - minute (60 seconds)
h - hour (60 minutes)
d - day (24 hours)
w - week (7 days)
```
*Larger units probably won't be needed. Also, their addition won't be trivial, because of their variable durations. (Those can be safely ignored in the above units, nobody is going to care about random leap second.)*

The pattern itself can be formally defined by following pseudo-regex:
```
[?!]?<u>' '?('"'[^"]+'"')?'s'?
```
In words:
1. Pattern itself may be prefixed with  '?' or with '!'. This signifies, that this format should only be printed if some condition is met. If this leads to the format not being printed and the `{{pattern}}` is on each side surrounded by ` ` space, one space is then dropped, to prevent unsightly double-spaces.
    - '?' print only if not zero or all present larger units **are not** zero (to hide leading zeroes)
    - '!' print only if all larger present units **are** zero (to hide unnecessary detail)
1. Single unit-letter which specifies about which unit this pattern is about
1. Then an optional space character, which, if present, denotes that there should be a space between the number and unit string
1. Then, optionally, arbitrary string enclosed in `"` (the string may not contain `"`). This string will be used instead of the default unit (which is the unit-letter itself).
1. Then, optionally, single letter 's' to denote that the unit string should have `s` appended, if the value is not `1`.

For example (time formatted is 7301 seconds, that is 2 hours, 1 minute and 41 seconds):
```
#time {{w}} {{d}} {{h}} {{m}}
```
generates the following: `#time 0w 0d 2h 1m`. More examples:
```
Took {{?h "hour"s}} {{?m "minute"s}} {{!s "second"s}}
```
produces (the current behavior): `Took 2 hours 1 minute`

This format string could be also used to customize the text displayed in the IDE widget.

**Comment by briggleman** [comment]
Agreed.  This is excellent and captures the request perfectly.

**Comment by cautionbug** [comment]
Came in to request this exact feature.

Will the proposed formatting work for commit templates in general? My team (currently) uses YouTrack, and we'd like to start applying worked time in the YouTrack commands issued from commits. So a template (Settings > Tools > Tasks > Servers > Commit Message) like this:
```
^{id} State Fixed ... Worked {{d}} {{h}} {{m}}
```
would be fantastic.

Or is that not possible given the first stipulation?
>Time will be always appended as the last line of the commit message

It would seem to me that making the time values more "portable" within the commit message would really make this feature shine. Maybe that requires additional template/expression matching, for a block that looks like (for example):
```
<#DTT {{d}} {{m}}>
```
So that a commit message template like the one above would become:
```
^{id} State Fixed ... Worked <#DTT {{d}} {{h}} {{m}}>
```
and result would be:
```
^PROJ-1234 State Fixed ... Worked 2h 45m
```
i don't know what would be practical as a "container", but it would definitely be helpful to be able to place the time results anywhere i want to within the commit message.

**Comment by Darkyenus** [comment]
I am not sure how commit templates work, but I think that it should be possible to allow the time log to be inserted at arbitrary spot in the message. Btw. can you please give me a link with a specification of the "Worked" command? Just to make sure I understand everything correctly when I get around to implement it.

**Comment by cautionbug** [comment]
* [YouTrack Custom Field Types](https://www.jetbrains.com/help/youtrack/standalone/Supported-Custom-Field-Types.html)
* [YouTrack Task Management](https://www.jetbrains.com/help/youtrack/standalone/Task-Management-Plugin.html)
* [YouTrack Command Reference](https://www.jetbrains.com/help/youtrack/standalone/Command-Reference.html)

For YouTrack, a command is a full line that starts with a "tagged" Issue ID. In my previous example, the `^` character tags `PROJ-1234` and indicates a command is being issued. Everything after that is parsed by YouTrack for field names/aliases and values to assign. Virtually anything valid from the Command Reference link above can be applied in a commit message.

`Worked` is an alias for the `Spent Time` field, and the example command will set `2h 45m` as its value (or increase an existing value by that much). It accepts the same duration format you had already laid out, so i don't think there's a problem there. Essentially, for this situation, being able to template just the time values with no additional text would be excellent.

The commit template is just a block of text used for the commit when you're working through a task. It accepts certain variables depending on the issue server you've linked to so it can auto fill some values for you. The template gets values swapped in when you use the IDE's commit dialog, so before the actual `git commit ...` is issued. If i understand your plugin correctly, the work time is being replaced at the tail end of the commit process, so i don't *think* it would interfere.

Hope that helps. Let me know if more info is needed.

**Comment by alanalvarado** [comment]
Your plugin is one of the best I've tried
Custom templates for injecting the time would be awesome, I use GitLab, and Microsoft Team Services.

Gitlab uses the next format: /spend 3h 22m
But the format might change soon when they ship the feature to track time from commits.
https://docs.gitlab.com/ee/workflow/time_tracking.html

So this would be a nice addition.

**Comment by joshnewlinatclearobject** [comment]
I'm going to bump this thread just because I think this would be a useful feature, specifically regarding the Jira implementation of `#time 5m`.

**Comment by Darkyenus** [comment]
Added by 3b7a047f921767dbbd0903cca9e979847b790737 (and other commits).

**Comment by briggleman** [comment]
@Darkyenus thanks!
