### ISSUE TITLE
Git integration does not work when git repository has unusual configuration or location

### ISSUE THREAD

**Issue by hosswald** [Darkyenus/DarkyenusTimeTracker#20]
When I try to enable commit work time injection, I get the following error message:
![image](https://user-images.githubusercontent.com/32925139/45440712-4f481b80-b6bd-11e8-81a5-f9149fa7e0f5.png)
My IDEA Git settings:
![image](https://user-images.githubusercontent.com/32925139/45440737-62f38200-b6bd-11e8-82c4-a35ab1cc0012.png)
I'm using IntelliJ IDEA 2018.3 EAP (Ultimate Edition) Build #IU-183.2153.8.
I'm happy to provide additional information if neccessary.

**Comment by Darkyenus** [comment]
This message appears because you don't have `.git/hooks` directory in the root directory of your project. This most likely happens because your project directory is not a git repository root directory, either because your project does not use git yet, or because you use a different (possibly parent) directory as the git respository root. The plugin is not currently able to handle such cases.

If you are not sure what applies to you, please send a screenshot of your Settings -> Version Control (not Settings -> Version Control -> Git). For the git integration to work, it should look something like this:
<img width="711" alt="screen shot 2018-09-13 at 12 13 50" src="https://user-images.githubusercontent.com/5280068/45482521-a0542000-b74e-11e8-92a5-c8257aefd372.png">

**Comment by hosswald** [comment]
@Darkyenus thanks for your reply. My project is registered in IDEA, the screen looks just like that:
![image](https://user-images.githubusercontent.com/32925139/45483176-726fdb00-b750-11e8-9352-476b9c3fbcb5.png)
Considering your explanation, the reason it doesn't work will be that I use [`git worktree`](https://git-scm.com/docs/git-worktree). Instead of a `.git/` folder I have a `.git` file with the content
`gitdir: ../somepath.git/worktrees/somename` (I have multiple worktrees using `../somepath.git`).
I assume it would be easy to use `../somepath.git/hooks` instead of `.git/hooks` in such cases.
Thanks for your work.

**Comment by Darkyenus** [comment]
I see, I will probably just let users browse to `.git/(hooks)` manually when the default is not found, as there is a lot of different ways to configure git and this should cover all of them. Who is knowledgeable enough to be able to setup git in one of these ways will probably not mind having to set it up manually.

**Comment by hosswald** [comment]
@Darkyenus I just installed the update but I can't find an option anywhere to set the `hooks` path.

**Comment by hosswald** [comment]
The balloon doesn't offer any action on my IDEA build (2013.3 EAP):
![image](https://user-images.githubusercontent.com/32925139/45741078-003b4280-bbf7-11e8-9366-3926a08a887c.png)
Also, it initially appears behind the tool popup and is hard to detect if you don't know it's there:
![image](https://user-images.githubusercontent.com/32925139/45741006-d84bdf00-bbf6-11e8-91e6-ab9b5d13a310.png)

**Comment by Darkyenus** [comment]
This happens when there is no `.git` folder at all. But thinking about it, it still should be possible to use it in that case and there are probably still some problems in the hook script when it is in a different folder.
