### ISSUE TITLE
Error zeroing

### ISSUE THREAD

**Issue by evgarik** [Darkyenus/DarkyenusTimeTracker#3]
in .darkyenus_time_tracker_commit_time file write 0, but when updating the recording time does not include the value and continues to count

**Comment by evgarik** [comment]
i use IntelliJ IDEA 2016.3.4 and AndroidStudio 2.2

**Comment by Darkyenus** [comment]
I am not sure if I understand correctly.
`.darkyenus_time_tracker_commit_time` is used only for git integration, changing it's content won't reflect in any way in the IDE widget time.

To be clear: Plugin time is stored in `.idea/workspace.xml`. When IDE changes focus, time since last change is added to the `.darkyenus_time_tracker_commit_time` file. Changing value stored in `workspace.xml` will change the value in the IDE (if the IDE is NOT running). Changing the value in `.darkyenus_time_tracker_commit_time` will not be visible in the IDE, but will be visible when commiting.

If you still believe there is an error, please answer these questions:

- What are you doing?
- What do you expect to happen?
- What happens?

Thank you!

**Comment by evgarik** [comment]
1. Press commit
2. I expect that for the next commit will begin with 0
3. Time is growing at commits

When monitoring file .darkyenus_time_tracker_commit_time discovered that he entered 0, but the timer in the calculation does not account for the value

**Comment by evgarik** [comment]
monitoring exercised command
`tail -f .darkyenus_time_tracker_commit_time`

**Comment by evgarik** [comment]
maybe there is a situation of simultaneous read and write file

**Comment by jIRKA-232** [comment]
If I understand correctly, what you are saying is time tracking widget does not reset to 0 when you make a commit, is that right?
That is expected behavior - widget in IDE shows how much time you have spent on your project - that means it is not supposed to reset with every commit. Commit time counter (.darkyenus_time_tracker_commit_time file) however resets with every commit because when you make non-merge commit, it appends message saying time you spent working only on that specific commit.
When you make commit afterwards, it should show time between last and this commit, but it does not affect widget counter in IDE

**Comment by evgarik** [comment]
Sorry for my English.
You have correctly understood everything.
The fact that the command
`echo "0"> $ {DTT_TIME}`
I see there add 0 to file .darkyenus_time_tracker_commit_time
but then it puts a widget while not taking into account that the count should locality starting from 0

**Comment by evgarik** [comment]
if I execute the command terminal
echo "0"> .darkyenus_time_tracker_commit_time
the countdown begins again

**Comment by evgarik** [comment]
I realized that when the widget is already considered the file,
there is a record of prepare-commit-msg echo command (what I see)
and then writes the new value of the widget.
so and so turns.
You can stop the work of the widget is open other windows?

**Comment by evgarik** [comment]
widget should go into idle status when I open other windows in the IDE?

**Comment by evgarik** [comment]
If, during the confirmation of the commit wait when the IDE enters IDLE status, everything works!

**Comment by Darkyenus** [comment]
Please don't post multiple comments, notifications get very noisy. If you want, you can edit them.

Plugin does not track changes of the `.darkyenus_time_tracker_commit_time` file. This file contains only time it took to make latest commit, plugin/IDE/wdiget does not care about that. Widget shows total time spent on the project, across commits.

When you stop the timer by clicking the widget (or it stops by going into "idle" state), or when the IDE decides to save documents (which is usually when you change focus of/inside the IDE), more time is added to the `.darkyenus_time_tracker_commit_time` file (if the timer was running, of course).

`.darkyenus_time_tracker_commit_time` file is not changed anytime else, because writing files continuously is somewhat slow and CPU/HDD "intensive". If you want to force update the `.darkyenus_time_tracker_commit_time` file, click the widget two times (to stop and restart the tracking). Doing "Save All" action (Ctrl+S, or Cmd+S on macOS) should also work.

**Comment by evgarik** [comment]
We are sorry for the inconvenience.
The widget should cause the state to IDLE when opening windows commit?
I will not go into IDLE :(

**Comment by Darkyenus** [comment]
Tracker will go into idle (yellow) mode only after some time of inactivity. The time required can be changed in the configuration menu, right click the widget.

Since I am not aware of any issue, I'm closing this issue for now, at least until I become aware of any issue. You can send me an email if you want, I'll be happy to help if you have any further questions.
