### ISSUE TITLE
Update time when time-tracking-file is changed externally

### ISSUE THREAD

**Issue by 0leksandr** [Darkyenus/DarkyenusTimeTracker#39]
When I commit using terminal (externally, not using Idea commit dialog), commit message is being updated correctly, and time-tracking file (`.git/.darkyenus_time_tracker_commit_time`) is being reset correctly, but in IDE I still see time unchanged. So I have to reset it manually every time.
Am I missing some settings, or something?

**Comment by Darkyenus** [comment]
The time in IDE and the time for commits is independent of each other. The way I use it is that I keep the total time (or some other longer period of time) in the IDE counter and the time in commit messages is just the time it took to create that one commit.

There is no easy and robust way to detect commits from the IDE, so I don't expect this to change in the forseeable future.

But I can see how it could be confusing, I'll add more documentation about it.

**Comment by 0leksandr** [comment]
Thank you! What I thought at first sight (but didn't really get into deeply) - is that plugin might have tracked changes of time-tracking-file (like [watchdog](https://pypi.org/project/watchdog/) or [fsnotify](https://github.com/fsnotify/fsnotify) do), and respectfully update in-app time. But this is only a proposal and first primitive thought :upside_down_face:

**Comment by Darkyenus** [comment]
That would be a way to implement it (special care would have to be taken to make sure that it works even when the modification happens when the IDE is not running), but right now I actually prefer the current behavior, even if it is a bit confusing at first. But what you describe could exist as an option in the future.

**Comment by 0leksandr** [comment]
Another issue (connected to the original one): switching branches is equivalent to switching tasks to me (but this might not be true for any other person, of course). When I work on, say, branch A for 5 minutes, then checkout to new branch B, I'd like time-track to be updated (reset to 0, if I just created branch). After I worked on branch B for 10 minutes, and then checkout to branch A, I'd like the time-track to be updated to 5 minutes again, and so on.
Again, this is very personal, but there _might_ be a silver bullet to both issues (and potentially, some others): what if the plugin would not just update the time-tracking-file every second, and display it, but read, add 1 second (or another interval), and then write+display?
On one hand, it should not affect current functionality of the plugin (correct me if I'm wrong), and should not break the idea - tracking time, spent on a task in the IDE (again, correct me if I got it wrong). On the other hand, it gives users the possibility to modify the behaviour of the plugin accordingly to their needs (like in my second case, I could save/restore time-tracking-file when I checkout to another branch, and be sure, that change is being reflected in the plugin).
I'd be glad to hear your thoughts.

**Comment by Darkyenus** [comment]
I believe something like this was already discussed in other issues. In general it would be nice if something like this was supported, but it is very tricky if not impossible to implement it robustly, because it requires an atomic coordination of multiple systems, some of which are in git binaries, some are in Java and some in bash, and there is no simple way to do that.

I'd also like to keep the project as simple as possible, at least for now. So if you need something more complex, you may need to look for a more complete time tracking solution elsewhere, sorry.

**Comment by 0leksandr** [comment]
Oh, that makes sense, I see. Thanks for the answer!
