### ISSUE TITLE
Reset After Commit

### ISSUE THREAD

**Issue by Bremaweb** [Darkyenus/DarkyenusTimeTracker#40]
Thanks for a great plugin. The last thing I feel like it needs so you can set it up and just forget about it is an automatic reset after commit. When I commit and it adds the time to the commit message I would like it to automatically reset the time to 0. I know I'm going to forget to reset it to start timing my next commit and that's going to inflate the time.

**Comment by Darkyenus** [comment]
The comit timer is independent from the IDE timer. So if you use only the commit timer to inject time into commits, you don't have to worry about the IDE time at all.

Example:
- Work for 1 hour, commit timer is now at 1h, IDE timer shows 1h
- Commit: "Took 1 hour", commit timer reset, IDE timer shows 1h
- Work another 1 hour, commit timer now at 1h, IDE timer shows 2h
- Commit: "Took 1 hour", commit timer reset, IDE timer shows 2h

Because of the way the system works under the hood, it is tricky to reset the IDE timer with the commit timer, so it is unlikely to be implemented anytime soon. (And the current system fits my workflow, but I understand that others may have a different workflows.)
